spring:

  h2:
    console:
      enabled: true

  datasource:
    # H2 DB 메모리 상에서 사용
    url: jdbc:h2:mem:instagramclone
    # 접속을 위한 드라이버
    driver-class-name: org.h2.Driver
    # SpringBoot 2.4부터 username 필수
    username: sa
    password:

  security:
    oauth2:
      client:
        registration:
          google:
            #github push 불가능, id, secret key 제거 후 커밋
            #추후에 github에서 따로 설정 필요
            client-name: ${google}
            client-id:
            client-secret:
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    # create: 객체를 통해 자동 테이블 생성
    # drop: 종료 시 테이블 삭제
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
  
  # 콘솔 확인
  output:
    ansi:
      enabled: always

logging:
  level:
    com.project: DEBUG
    # 파라미터 확인
    org.hibernate.type: trace
    org.springframework.security: DEBUG